version: '3.8'
services:

  pgadmin:
    container_name: potato_pgadmin4
    image: dpage/pgadmin4
    restart: always
    expose:
      - 5050
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - ${PG_PORTS}
    networks:
      - mynet

  db:
    container_name: potato_postgres_db
    image: postgres
    restart: always
    user: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: test_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d test_db" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - .:/docker-entrypoint-initdb.d
    #      - ./db_schemas/db.sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynet

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test_db
      - SPRING_DATASOURCE_USERNAME=your-username
      - SPRING_DATASOURCE_PASSWORD=your-password

  maven:
    image: maven:latest
    volumes:
      - ./main:/java
    working_dir: /app

networks:
  mynet:
    driver: bridge

volumes:
  db:
    driver: local